# Default values for the application
DEFAULT_PEPTIDE = '[Acetyl]-PEPTIDES[UNIMOD:21]'
DEFAULT_CHARGE = 2
DEFAULT_MASS_TYPE = 'monoisotopic'
DEFAULT_FRAGMENT_TYPES = {'a','b', 'x', 'y'}
DEFAULT_USE_MASS_BOUNDS = False
DEFAULT_MIN_MZ = 150.0
DEFAULT_MAX_MZ = 2000.0
DEFAULT_PRECISION = 5
DEFAULT_ROW_PADDING = 5
DEFAULT_COLUMN_PADDING = 8
DEFAULT_SHOW_BORDERS = False
DEFAULT_A_COLOR = '#8c564b'
DEFAULT_B_COLOR = '#1f77b4'
DEFAULT_C_COLOR = '#2ca02c'
DEFAULT_X_COLOR = '#ff7f0e'
DEFAULT_Y_COLOR = '#d62728'
DEFAULT_Z_COLOR = '#9467bd'